apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv-volume
  namespace: test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/tomaer/.k8s_volume/redis/data"